2018-07-03 00:59:39
Model(s): ['xgb']
Sim Start Day: 170
Training feature minutes: [1, 5, 10, 20, 30, 40, 50, 60, 120, 240, 480, 960]
Training Min(s): ['none']
Test Min(s): [1440]
Poly(s): [3]
Coin feature configuration: {'ethusdt': 'target', 'btcusdt': 'alt', 'trxeth': 'through'}
/mnt/src/lib/market_maker_training.py:45: DtypeWarning: Columns (41,42,44,45,50,51,53,54,59,60,62,63,68,69,71,72,77,78,80,81,86,87,89,90,95,96,98,99,104,105,107,108,113,114,116,117,122,123,125,126,131,132,134,135,140,141,143,144,149,150,152,153,158,159,161,162,167,168,170,171,176,177,179,180,185,186,188,189,194,195,197,198,203,204,206,207,212,213,215,216,221,222,224,225,230,231,233,234,239,240,242,243,248,249,251,252,257,258,260,261,266,267,269,270,275,276,278,279,284,285,287,288,293,294,296,297,302,303,305,306,311,312,314,315,320,321,323,324,329,330,332,333,338,339,341,342,347,348,350,351,356,357,359,360) have mixed types. Specify dtype option on import or set low_memory=False.
  features_df = athena.pandas_read_athena(training_data_sql)
(259196, 365)
Model: xgb
2018-07-03 01:05:38
Number of days to iterate: 11
Traceback (most recent call last):
  File "notebooks/return_simulation.py", line 236, in <module>
    main()
  File "notebooks/return_simulation.py", line 115, in main
    poly_degree=polynomial) for interval in range(int(test_intervals)))
  File "/usr/local/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 962, in __call__
    self.retrieve()
  File "/usr/local/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 865, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 515, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/anaconda/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 431, in result
    return self.__get_result()
  File "/usr/local/anaconda/lib/python3.6/site-packages/joblib/externals/loky/_base.py", line 382, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A process in the executor was terminated abruptly while the future was running or pending.
Failed with exit code: 1
